<?php
/**
 * InstrumentsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LORIS REST API
 *
 * LORIS REST API and Module endpoints.  ## Server Configuration  | Type | Configuration | Endpoints | |------|---------------|-----------| | REST API | `setHost(\"{$baseUrl}/api/{$version}\")` | /login, /candidates, /projects, /sites | | Module | `setHost($baseUrl)` | /instrument_manager/_* |
 *
 * The version of the OpenAPI document: 0.0.4-dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LORISClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use LORISClient\ApiException;
use LORISClient\Configuration;
use LORISClient\FormDataProcessor;
use LORISClient\HeaderSelector;
use LORISClient\ObjectSerializer;

/**
 * InstrumentsApi Class Doc Comment
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InstrumentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getInstrumentData' => [
            'application/json',
        ],
        'getVisitInstruments' => [
            'application/json',
        ],
        'patchInstrumentData' => [
            'application/json',
        ],
        'putInstrumentData' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getInstrumentData
     *
     * Get instrument data
     *
     * @param  string $candid candid (required)
     * @param  string $visit visit (required)
     * @param  string $instrument instrument (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstrumentData'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LORISClient\Model\InstrumentData
     */
    public function getInstrumentData($candid, $visit, $instrument, string $contentType = self::contentTypes['getInstrumentData'][0])
    {
        list($response) = $this->getInstrumentDataWithHttpInfo($candid, $visit, $instrument, $contentType);
        return $response;
    }

    /**
     * Operation getInstrumentDataWithHttpInfo
     *
     * Get instrument data
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstrumentData'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LORISClient\Model\InstrumentData, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInstrumentDataWithHttpInfo($candid, $visit, $instrument, string $contentType = self::contentTypes['getInstrumentData'][0])
    {
        $request = $this->getInstrumentDataRequest($candid, $visit, $instrument, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LORISClient\Model\InstrumentData',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LORISClient\Model\InstrumentData',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LORISClient\Model\InstrumentData',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getInstrumentDataAsync
     *
     * Get instrument data
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstrumentData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInstrumentDataAsync($candid, $visit, $instrument, string $contentType = self::contentTypes['getInstrumentData'][0])
    {
        return $this->getInstrumentDataAsyncWithHttpInfo($candid, $visit, $instrument, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getInstrumentDataAsyncWithHttpInfo
     *
     * Get instrument data
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstrumentData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInstrumentDataAsyncWithHttpInfo($candid, $visit, $instrument, string $contentType = self::contentTypes['getInstrumentData'][0])
    {
        $returnType = '\LORISClient\Model\InstrumentData';
        $request = $this->getInstrumentDataRequest($candid, $visit, $instrument, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getInstrumentData'
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInstrumentData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getInstrumentDataRequest($candid, $visit, $instrument, string $contentType = self::contentTypes['getInstrumentData'][0])
    {

        // verify the required parameter 'candid' is set
        if ($candid === null || (is_array($candid) && count($candid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $candid when calling getInstrumentData'
            );
        }

        // verify the required parameter 'visit' is set
        if ($visit === null || (is_array($visit) && count($visit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $visit when calling getInstrumentData'
            );
        }

        // verify the required parameter 'instrument' is set
        if ($instrument === null || (is_array($instrument) && count($instrument) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $instrument when calling getInstrumentData'
            );
        }


        $resourcePath = '/candidates/{candid}/{visit}/instruments/{instrument}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($candid !== null) {
            $resourcePath = str_replace(
                '{' . 'candid' . '}',
                ObjectSerializer::toPathValue($candid),
                $resourcePath
            );
        }
        // path params
        if ($visit !== null) {
            $resourcePath = str_replace(
                '{' . 'visit' . '}',
                ObjectSerializer::toPathValue($visit),
                $resourcePath
            );
        }
        // path params
        if ($instrument !== null) {
            $resourcePath = str_replace(
                '{' . 'instrument' . '}',
                ObjectSerializer::toPathValue($instrument),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getVisitInstruments
     *
     * List instruments for a visit
     *
     * @param  string $candid candid (required)
     * @param  string $visit visit (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVisitInstruments'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LORISClient\Model\VisitInstrumentsResponse
     */
    public function getVisitInstruments($candid, $visit, string $contentType = self::contentTypes['getVisitInstruments'][0])
    {
        list($response) = $this->getVisitInstrumentsWithHttpInfo($candid, $visit, $contentType);
        return $response;
    }

    /**
     * Operation getVisitInstrumentsWithHttpInfo
     *
     * List instruments for a visit
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVisitInstruments'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LORISClient\Model\VisitInstrumentsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getVisitInstrumentsWithHttpInfo($candid, $visit, string $contentType = self::contentTypes['getVisitInstruments'][0])
    {
        $request = $this->getVisitInstrumentsRequest($candid, $visit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LORISClient\Model\VisitInstrumentsResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LORISClient\Model\VisitInstrumentsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LORISClient\Model\VisitInstrumentsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getVisitInstrumentsAsync
     *
     * List instruments for a visit
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVisitInstruments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVisitInstrumentsAsync($candid, $visit, string $contentType = self::contentTypes['getVisitInstruments'][0])
    {
        return $this->getVisitInstrumentsAsyncWithHttpInfo($candid, $visit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getVisitInstrumentsAsyncWithHttpInfo
     *
     * List instruments for a visit
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVisitInstruments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVisitInstrumentsAsyncWithHttpInfo($candid, $visit, string $contentType = self::contentTypes['getVisitInstruments'][0])
    {
        $returnType = '\LORISClient\Model\VisitInstrumentsResponse';
        $request = $this->getVisitInstrumentsRequest($candid, $visit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getVisitInstruments'
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getVisitInstruments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getVisitInstrumentsRequest($candid, $visit, string $contentType = self::contentTypes['getVisitInstruments'][0])
    {

        // verify the required parameter 'candid' is set
        if ($candid === null || (is_array($candid) && count($candid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $candid when calling getVisitInstruments'
            );
        }

        // verify the required parameter 'visit' is set
        if ($visit === null || (is_array($visit) && count($visit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $visit when calling getVisitInstruments'
            );
        }


        $resourcePath = '/candidates/{candid}/{visit}/instruments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($candid !== null) {
            $resourcePath = str_replace(
                '{' . 'candid' . '}',
                ObjectSerializer::toPathValue($candid),
                $resourcePath
            );
        }
        // path params
        if ($visit !== null) {
            $resourcePath = str_replace(
                '{' . 'visit' . '}',
                ObjectSerializer::toPathValue($visit),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchInstrumentData
     *
     * Update instrument data
     *
     * @param  string $candid candid (required)
     * @param  string $visit visit (required)
     * @param  string $instrument instrument (required)
     * @param  \LORISClient\Model\InstrumentDataRequest $instrumentDataRequest instrumentDataRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchInstrumentData'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LORISClient\Model\InstrumentData
     */
    public function patchInstrumentData($candid, $visit, $instrument, $instrumentDataRequest, string $contentType = self::contentTypes['patchInstrumentData'][0])
    {
        list($response) = $this->patchInstrumentDataWithHttpInfo($candid, $visit, $instrument, $instrumentDataRequest, $contentType);
        return $response;
    }

    /**
     * Operation patchInstrumentDataWithHttpInfo
     *
     * Update instrument data
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  \LORISClient\Model\InstrumentDataRequest $instrumentDataRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchInstrumentData'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LORISClient\Model\InstrumentData, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchInstrumentDataWithHttpInfo($candid, $visit, $instrument, $instrumentDataRequest, string $contentType = self::contentTypes['patchInstrumentData'][0])
    {
        $request = $this->patchInstrumentDataRequest($candid, $visit, $instrument, $instrumentDataRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LORISClient\Model\InstrumentData',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LORISClient\Model\InstrumentData',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LORISClient\Model\InstrumentData',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation patchInstrumentDataAsync
     *
     * Update instrument data
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  \LORISClient\Model\InstrumentDataRequest $instrumentDataRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchInstrumentData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchInstrumentDataAsync($candid, $visit, $instrument, $instrumentDataRequest, string $contentType = self::contentTypes['patchInstrumentData'][0])
    {
        return $this->patchInstrumentDataAsyncWithHttpInfo($candid, $visit, $instrument, $instrumentDataRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchInstrumentDataAsyncWithHttpInfo
     *
     * Update instrument data
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  \LORISClient\Model\InstrumentDataRequest $instrumentDataRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchInstrumentData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchInstrumentDataAsyncWithHttpInfo($candid, $visit, $instrument, $instrumentDataRequest, string $contentType = self::contentTypes['patchInstrumentData'][0])
    {
        $returnType = '\LORISClient\Model\InstrumentData';
        $request = $this->patchInstrumentDataRequest($candid, $visit, $instrument, $instrumentDataRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchInstrumentData'
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  \LORISClient\Model\InstrumentDataRequest $instrumentDataRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchInstrumentData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchInstrumentDataRequest($candid, $visit, $instrument, $instrumentDataRequest, string $contentType = self::contentTypes['patchInstrumentData'][0])
    {

        // verify the required parameter 'candid' is set
        if ($candid === null || (is_array($candid) && count($candid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $candid when calling patchInstrumentData'
            );
        }

        // verify the required parameter 'visit' is set
        if ($visit === null || (is_array($visit) && count($visit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $visit when calling patchInstrumentData'
            );
        }

        // verify the required parameter 'instrument' is set
        if ($instrument === null || (is_array($instrument) && count($instrument) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $instrument when calling patchInstrumentData'
            );
        }

        // verify the required parameter 'instrumentDataRequest' is set
        if ($instrumentDataRequest === null || (is_array($instrumentDataRequest) && count($instrumentDataRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $instrumentDataRequest when calling patchInstrumentData'
            );
        }


        $resourcePath = '/candidates/{candid}/{visit}/instruments/{instrument}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($candid !== null) {
            $resourcePath = str_replace(
                '{' . 'candid' . '}',
                ObjectSerializer::toPathValue($candid),
                $resourcePath
            );
        }
        // path params
        if ($visit !== null) {
            $resourcePath = str_replace(
                '{' . 'visit' . '}',
                ObjectSerializer::toPathValue($visit),
                $resourcePath
            );
        }
        // path params
        if ($instrument !== null) {
            $resourcePath = str_replace(
                '{' . 'instrument' . '}',
                ObjectSerializer::toPathValue($instrument),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($instrumentDataRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($instrumentDataRequest));
            } else {
                $httpBody = $instrumentDataRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putInstrumentData
     *
     * Replace instrument data
     *
     * @param  string $candid candid (required)
     * @param  string $visit visit (required)
     * @param  string $instrument instrument (required)
     * @param  \LORISClient\Model\InstrumentDataRequest $instrumentDataRequest instrumentDataRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putInstrumentData'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LORISClient\Model\InstrumentData
     */
    public function putInstrumentData($candid, $visit, $instrument, $instrumentDataRequest, string $contentType = self::contentTypes['putInstrumentData'][0])
    {
        list($response) = $this->putInstrumentDataWithHttpInfo($candid, $visit, $instrument, $instrumentDataRequest, $contentType);
        return $response;
    }

    /**
     * Operation putInstrumentDataWithHttpInfo
     *
     * Replace instrument data
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  \LORISClient\Model\InstrumentDataRequest $instrumentDataRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putInstrumentData'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LORISClient\Model\InstrumentData, HTTP status code, HTTP response headers (array of strings)
     */
    public function putInstrumentDataWithHttpInfo($candid, $visit, $instrument, $instrumentDataRequest, string $contentType = self::contentTypes['putInstrumentData'][0])
    {
        $request = $this->putInstrumentDataRequest($candid, $visit, $instrument, $instrumentDataRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LORISClient\Model\InstrumentData',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LORISClient\Model\InstrumentData',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LORISClient\Model\InstrumentData',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation putInstrumentDataAsync
     *
     * Replace instrument data
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  \LORISClient\Model\InstrumentDataRequest $instrumentDataRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putInstrumentData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putInstrumentDataAsync($candid, $visit, $instrument, $instrumentDataRequest, string $contentType = self::contentTypes['putInstrumentData'][0])
    {
        return $this->putInstrumentDataAsyncWithHttpInfo($candid, $visit, $instrument, $instrumentDataRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation putInstrumentDataAsyncWithHttpInfo
     *
     * Replace instrument data
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  \LORISClient\Model\InstrumentDataRequest $instrumentDataRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putInstrumentData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putInstrumentDataAsyncWithHttpInfo($candid, $visit, $instrument, $instrumentDataRequest, string $contentType = self::contentTypes['putInstrumentData'][0])
    {
        $returnType = '\LORISClient\Model\InstrumentData';
        $request = $this->putInstrumentDataRequest($candid, $visit, $instrument, $instrumentDataRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putInstrumentData'
     *
     * @param  string $candid (required)
     * @param  string $visit (required)
     * @param  string $instrument (required)
     * @param  \LORISClient\Model\InstrumentDataRequest $instrumentDataRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putInstrumentData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putInstrumentDataRequest($candid, $visit, $instrument, $instrumentDataRequest, string $contentType = self::contentTypes['putInstrumentData'][0])
    {

        // verify the required parameter 'candid' is set
        if ($candid === null || (is_array($candid) && count($candid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $candid when calling putInstrumentData'
            );
        }

        // verify the required parameter 'visit' is set
        if ($visit === null || (is_array($visit) && count($visit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $visit when calling putInstrumentData'
            );
        }

        // verify the required parameter 'instrument' is set
        if ($instrument === null || (is_array($instrument) && count($instrument) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $instrument when calling putInstrumentData'
            );
        }

        // verify the required parameter 'instrumentDataRequest' is set
        if ($instrumentDataRequest === null || (is_array($instrumentDataRequest) && count($instrumentDataRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $instrumentDataRequest when calling putInstrumentData'
            );
        }


        $resourcePath = '/candidates/{candid}/{visit}/instruments/{instrument}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($candid !== null) {
            $resourcePath = str_replace(
                '{' . 'candid' . '}',
                ObjectSerializer::toPathValue($candid),
                $resourcePath
            );
        }
        // path params
        if ($visit !== null) {
            $resourcePath = str_replace(
                '{' . 'visit' . '}',
                ObjectSerializer::toPathValue($visit),
                $resourcePath
            );
        }
        // path params
        if ($instrument !== null) {
            $resourcePath = str_replace(
                '{' . 'instrument' . '}',
                ObjectSerializer::toPathValue($instrument),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($instrumentDataRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($instrumentDataRequest));
            } else {
                $httpBody = $instrumentDataRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
