<?php
/**
 * InstrumentManagerApi
 * PHP version 8.1
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LORIS - REST API endpoints
 *
 * LORIS REST API for clinical data ingestion and management. Standard HTTP error codes are used. Responses contain either an empty body or a JSON object.
 *
 * The version of the OpenAPI document: 0.0.4-dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LORISClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use LORISClient\ApiException;
use LORISClient\Configuration;
use LORISClient\FormDataProcessor;
use LORISClient\HeaderSelector;
use LORISClient\ObjectSerializer;

/**
 * InstrumentManagerApi Class Doc Comment
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InstrumentManagerApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'instrumentManagerInstrumentDataGet' => [
            'application/json',
        ],
        'instrumentManagerInstrumentDataPost' => [
            'multipart/form-data',
        ],
        'instrumentManagerPost' => [
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation instrumentManagerInstrumentDataGet
     *
     * Generate expected CSV headers for instrument data ingestion
     *
     * @param  string $action CREATE_SESSIONS (creates missing sessions) or VALIDATE_SESSIONS (requires sessions exist) (required)
     * @param  string|null $instrument Single instrument name (optional)
     * @param  string|null $instruments Comma-separated list of instruments (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerInstrumentDataGet'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SplFileObject|\LORISClient\Model\ErrorResponse
     */
    public function instrumentManagerInstrumentDataGet($action, $instrument = null, $instruments = null, string $contentType = self::contentTypes['instrumentManagerInstrumentDataGet'][0])
    {
        list($response) = $this->instrumentManagerInstrumentDataGetWithHttpInfo($action, $instrument, $instruments, $contentType);
        return $response;
    }

    /**
     * Operation instrumentManagerInstrumentDataGetWithHttpInfo
     *
     * Generate expected CSV headers for instrument data ingestion
     *
     * @param  string $action CREATE_SESSIONS (creates missing sessions) or VALIDATE_SESSIONS (requires sessions exist) (required)
     * @param  string|null $instrument Single instrument name (optional)
     * @param  string|null $instruments Comma-separated list of instruments (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerInstrumentDataGet'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject|\LORISClient\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function instrumentManagerInstrumentDataGetWithHttpInfo($action, $instrument = null, $instruments = null, string $contentType = self::contentTypes['instrumentManagerInstrumentDataGet'][0])
    {
        $request = $this->instrumentManagerInstrumentDataGetRequest($action, $instrument, $instruments, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SplFileObject',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LORISClient\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SplFileObject',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LORISClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation instrumentManagerInstrumentDataGetAsync
     *
     * Generate expected CSV headers for instrument data ingestion
     *
     * @param  string $action CREATE_SESSIONS (creates missing sessions) or VALIDATE_SESSIONS (requires sessions exist) (required)
     * @param  string|null $instrument Single instrument name (optional)
     * @param  string|null $instruments Comma-separated list of instruments (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerInstrumentDataGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function instrumentManagerInstrumentDataGetAsync($action, $instrument = null, $instruments = null, string $contentType = self::contentTypes['instrumentManagerInstrumentDataGet'][0])
    {
        return $this->instrumentManagerInstrumentDataGetAsyncWithHttpInfo($action, $instrument, $instruments, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation instrumentManagerInstrumentDataGetAsyncWithHttpInfo
     *
     * Generate expected CSV headers for instrument data ingestion
     *
     * @param  string $action CREATE_SESSIONS (creates missing sessions) or VALIDATE_SESSIONS (requires sessions exist) (required)
     * @param  string|null $instrument Single instrument name (optional)
     * @param  string|null $instruments Comma-separated list of instruments (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerInstrumentDataGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function instrumentManagerInstrumentDataGetAsyncWithHttpInfo($action, $instrument = null, $instruments = null, string $contentType = self::contentTypes['instrumentManagerInstrumentDataGet'][0])
    {
        $returnType = '\SplFileObject';
        $request = $this->instrumentManagerInstrumentDataGetRequest($action, $instrument, $instruments, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'instrumentManagerInstrumentDataGet'
     *
     * @param  string $action CREATE_SESSIONS (creates missing sessions) or VALIDATE_SESSIONS (requires sessions exist) (required)
     * @param  string|null $instrument Single instrument name (optional)
     * @param  string|null $instruments Comma-separated list of instruments (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerInstrumentDataGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function instrumentManagerInstrumentDataGetRequest($action, $instrument = null, $instruments = null, string $contentType = self::contentTypes['instrumentManagerInstrumentDataGet'][0])
    {

        // verify the required parameter 'action' is set
        if ($action === null || (is_array($action) && count($action) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $action when calling instrumentManagerInstrumentDataGet'
            );
        }




        $resourcePath = '/instrument_manager/instrument_data';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $action,
            'action', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $instrument,
            'instrument', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $instruments,
            'instruments', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/octet-stream', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation instrumentManagerInstrumentDataPost
     *
     * Bulk insert instrument data from CSV
     *
     * @param  string $action action (required)
     * @param  \SplFileObject $dataFile dataFile (required)
     * @param  string|null $instrument instrument (optional)
     * @param  string|null $multiInstrument multiInstrument (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerInstrumentDataPost'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LORISClient\Model\InstrumentDataResponse|\LORISClient\Model\InstrumentDataResponse
     */
    public function instrumentManagerInstrumentDataPost($action, $dataFile, $instrument = null, $multiInstrument = null, string $contentType = self::contentTypes['instrumentManagerInstrumentDataPost'][0])
    {
        list($response) = $this->instrumentManagerInstrumentDataPostWithHttpInfo($action, $dataFile, $instrument, $multiInstrument, $contentType);
        return $response;
    }

    /**
     * Operation instrumentManagerInstrumentDataPostWithHttpInfo
     *
     * Bulk insert instrument data from CSV
     *
     * @param  string $action (required)
     * @param  \SplFileObject $dataFile (required)
     * @param  string|null $instrument (optional)
     * @param  string|null $multiInstrument (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerInstrumentDataPost'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LORISClient\Model\InstrumentDataResponse|\LORISClient\Model\InstrumentDataResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function instrumentManagerInstrumentDataPostWithHttpInfo($action, $dataFile, $instrument = null, $multiInstrument = null, string $contentType = self::contentTypes['instrumentManagerInstrumentDataPost'][0])
    {
        $request = $this->instrumentManagerInstrumentDataPostRequest($action, $dataFile, $instrument, $multiInstrument, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LORISClient\Model\InstrumentDataResponse',
                        $request,
                        $response,
                    );
                case 201:
                    return $this->handleResponseWithDataType(
                        '\LORISClient\Model\InstrumentDataResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LORISClient\Model\InstrumentDataResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LORISClient\Model\InstrumentDataResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LORISClient\Model\InstrumentDataResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation instrumentManagerInstrumentDataPostAsync
     *
     * Bulk insert instrument data from CSV
     *
     * @param  string $action (required)
     * @param  \SplFileObject $dataFile (required)
     * @param  string|null $instrument (optional)
     * @param  string|null $multiInstrument (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerInstrumentDataPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function instrumentManagerInstrumentDataPostAsync($action, $dataFile, $instrument = null, $multiInstrument = null, string $contentType = self::contentTypes['instrumentManagerInstrumentDataPost'][0])
    {
        return $this->instrumentManagerInstrumentDataPostAsyncWithHttpInfo($action, $dataFile, $instrument, $multiInstrument, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation instrumentManagerInstrumentDataPostAsyncWithHttpInfo
     *
     * Bulk insert instrument data from CSV
     *
     * @param  string $action (required)
     * @param  \SplFileObject $dataFile (required)
     * @param  string|null $instrument (optional)
     * @param  string|null $multiInstrument (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerInstrumentDataPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function instrumentManagerInstrumentDataPostAsyncWithHttpInfo($action, $dataFile, $instrument = null, $multiInstrument = null, string $contentType = self::contentTypes['instrumentManagerInstrumentDataPost'][0])
    {
        $returnType = '\LORISClient\Model\InstrumentDataResponse';
        $request = $this->instrumentManagerInstrumentDataPostRequest($action, $dataFile, $instrument, $multiInstrument, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'instrumentManagerInstrumentDataPost'
     *
     * @param  string $action (required)
     * @param  \SplFileObject $dataFile (required)
     * @param  string|null $instrument (optional)
     * @param  string|null $multiInstrument (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerInstrumentDataPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function instrumentManagerInstrumentDataPostRequest($action, $dataFile, $instrument = null, $multiInstrument = null, string $contentType = self::contentTypes['instrumentManagerInstrumentDataPost'][0])
    {

        // verify the required parameter 'action' is set
        if ($action === null || (is_array($action) && count($action) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $action when calling instrumentManagerInstrumentDataPost'
            );
        }

        // verify the required parameter 'dataFile' is set
        if ($dataFile === null || (is_array($dataFile) && count($dataFile) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $dataFile when calling instrumentManagerInstrumentDataPost'
            );
        }




        $resourcePath = '/instrument_manager/instrument_data';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'action' => $action,
            'instrument' => $instrument,
            'multiInstrument' => $multiInstrument,
            'dataFile' => $dataFile,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation instrumentManagerPost
     *
     * Install instrument from LINST file or REDCap CSV
     *
     * @param  \SplFileObject $installFile LINST or REDCap CSV instrument (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerPost'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LORISClient\Model\SuccessResponse|\LORISClient\Model\ErrorResponse
     */
    public function instrumentManagerPost($installFile, string $contentType = self::contentTypes['instrumentManagerPost'][0])
    {
        list($response) = $this->instrumentManagerPostWithHttpInfo($installFile, $contentType);
        return $response;
    }

    /**
     * Operation instrumentManagerPostWithHttpInfo
     *
     * Install instrument from LINST file or REDCap CSV
     *
     * @param  \SplFileObject $installFile LINST or REDCap CSV instrument (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerPost'] to see the possible values for this operation
     *
     * @throws \LORISClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LORISClient\Model\SuccessResponse|\LORISClient\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function instrumentManagerPostWithHttpInfo($installFile, string $contentType = self::contentTypes['instrumentManagerPost'][0])
    {
        $request = $this->instrumentManagerPostRequest($installFile, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\LORISClient\Model\SuccessResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LORISClient\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LORISClient\Model\SuccessResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LORISClient\Model\SuccessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LORISClient\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation instrumentManagerPostAsync
     *
     * Install instrument from LINST file or REDCap CSV
     *
     * @param  \SplFileObject $installFile LINST or REDCap CSV instrument (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function instrumentManagerPostAsync($installFile, string $contentType = self::contentTypes['instrumentManagerPost'][0])
    {
        return $this->instrumentManagerPostAsyncWithHttpInfo($installFile, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation instrumentManagerPostAsyncWithHttpInfo
     *
     * Install instrument from LINST file or REDCap CSV
     *
     * @param  \SplFileObject $installFile LINST or REDCap CSV instrument (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function instrumentManagerPostAsyncWithHttpInfo($installFile, string $contentType = self::contentTypes['instrumentManagerPost'][0])
    {
        $returnType = '\LORISClient\Model\SuccessResponse';
        $request = $this->instrumentManagerPostRequest($installFile, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'instrumentManagerPost'
     *
     * @param  \SplFileObject $installFile LINST or REDCap CSV instrument (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['instrumentManagerPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function instrumentManagerPostRequest($installFile, string $contentType = self::contentTypes['instrumentManagerPost'][0])
    {

        // verify the required parameter 'installFile' is set
        if ($installFile === null || (is_array($installFile) && count($installFile) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $installFile when calling instrumentManagerPost'
            );
        }


        $resourcePath = '/instrument_manager';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'installFile' => $installFile,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
