openapi: 3.0.1
info:
  title: LORIS REST API
  description: |
    LORIS REST API and Module endpoints.
    
    ## Server Configuration
    
    | Type | Configuration | Endpoints |
    |------|---------------|-----------|
    | REST API | `setHost("{$baseUrl}/api/{$version}")` | /login, /candidates, /projects, /sites |
    | Module | `setHost($baseUrl)` | /instrument_manager/* |
  contact:
    name: LORIS Development Team
    url: https://github.com/aces/Loris
  license:
    name: GNU Public License, Version 3
    url: https://opensource.org/licenses/GPL-3.0
  version: 0.0.4-dev

servers:
  - url: '{baseUrl}'
    variables:
      baseUrl:
        default: ''
        description: Set via Configuration::setHost()

security:
  - BearerAuth: []

paths:
  # ═══════════════════════════════════════════════════════════════════════════
  # AUTHENTICATION
  # ═══════════════════════════════════════════════════════════════════════════
  /login:
    post:
      tags: [Authentication]
      summary: Authenticate and obtain JWT token
      operationId: login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ═══════════════════════════════════════════════════════════════════════════
  # INSTRUMENT MANAGER (Module endpoints)
  # Configure: $config->setHost($baseUrl)  -- NO /api/{version}
  # ═══════════════════════════════════════════════════════════════════════════
  /instrument_manager:
    post:
      tags: [InstrumentManager]
      summary: Install instrument from LINST file or REDCap data dictionary
      operationId: installInstrument
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [install_file]
              properties:
                install_file:
                  type: string
                  format: binary
                  description: LINST file or REDCap CSV to install
      responses:
        '201':
          description: Instrument installed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Invalid file format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /instrument_manager/instrument_data:
    get:
      tags: [InstrumentManager]
      summary: Get expected CSV headers for instrument data upload
      operationId: getInstrumentDataHeaders
      parameters:
        - name: action
          in: query
          required: true
          schema:
            type: string
            enum: [CREATE_SESSIONS, VALIDATE_SESSIONS]
        - name: instrument
          in: query
          required: false
          schema:
            type: string
        - name: instruments
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: CSV template with headers
          content:
            text/csv:
              schema:
                type: string
        '400':
          description: Invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags: [InstrumentManager]
      summary: Bulk upload instrument data from CSV
      operationId: uploadInstrumentData
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [action, data_file]
              properties:
                action:
                  type: string
                  enum: [CREATE_SESSIONS, VALIDATE_SESSIONS]
                instrument:
                  type: string
                  description: Single instrument name
                multi-instrument:
                  type: string
                  description: Set to "true" for multi-instrument CSV
                data_file:
                  type: string
                  format: binary
                  description: CSV file with instrument data
      responses:
        '200':
          description: Validation errors occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentDataResponse'
        '201':
          description: Data inserted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentDataResponse'

  # ═══════════════════════════════════════════════════════════════════════════
  # CANDIDATES
  # ═══════════════════════════════════════════════════════════════════════════
  /candidates:
    get:
      tags: [Candidates]
      summary: List all candidates
      operationId: getCandidates
      responses:
        '200':
          description: List of candidates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidatesResponse'

    post:
      tags: [Candidates]
      summary: Create a new candidate
      operationId: createCandidate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CandidateCreateRequest'
      responses:
        '201':
          description: Candidate created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidateObject'
        '409':
          description: PSCID already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /candidates/{candid}:
    get:
      tags: [Candidates]
      summary: Get candidate details
      operationId: getCandidate
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Candidate details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidateObject'
        '404':
          description: Candidate not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ═══════════════════════════════════════════════════════════════════════════
  # VISITS
  # ═══════════════════════════════════════════════════════════════════════════
  /candidates/{candid}/{visit}:
    get:
      tags: [Visits]
      summary: Get visit details
      operationId: getVisit
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Visit details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisitObject'

    put:
      tags: [Visits]
      summary: Create a new visit
      operationId: createVisit
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VisitCreateRequest'
      responses:
        '201':
          description: Visit created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisitObject'
        '409':
          description: Visit already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ═══════════════════════════════════════════════════════════════════════════
  # INSTRUMENTS (per candidate/visit)
  # ═══════════════════════════════════════════════════════════════════════════
  /candidates/{candid}/{visit}/instruments:
    get:
      tags: [Instruments]
      summary: List instruments for a visit
      operationId: getVisitInstruments
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of instruments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisitInstrumentsResponse'

  /candidates/{candid}/{visit}/instruments/{instrument}:
    get:
      tags: [Instruments]
      summary: Get instrument data
      operationId: getInstrumentData
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
        - name: instrument
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Instrument data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentData'

    put:
      tags: [Instruments]
      summary: Replace instrument data
      operationId: putInstrumentData
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
        - name: instrument
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstrumentDataRequest'
      responses:
        '200':
          description: Data replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentData'

    patch:
      tags: [Instruments]
      summary: Update instrument data
      operationId: patchInstrumentData
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
        - name: instrument
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstrumentDataRequest'
      responses:
        '200':
          description: Data updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentData'

  # ═══════════════════════════════════════════════════════════════════════════
  # PROJECTS
  # ═══════════════════════════════════════════════════════════════════════════
  /projects:
    get:
      tags: [Projects]
      summary: List projects
      operationId: getProjects
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectsResponse'

  /projects/{project}:
    get:
      tags: [Projects]
      summary: Get project details
      operationId: getProject
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'

  /projects/{project}/instruments:
    get:
      tags: [Projects]
      summary: List project instruments
      operationId: getProjectInstruments
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Instruments list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentsResponse'

  # ═══════════════════════════════════════════════════════════════════════════
  # SITES
  # ═══════════════════════════════════════════════════════════════════════════
  /sites:
    get:
      tags: [Sites]
      summary: List sites
      operationId: getSites
      responses:
        '200':
          description: List of sites
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SitesResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
          format: password

    LoginResponse:
      type: object
      properties:
        token:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string

    SuccessResponse:
      type: object
      properties:
        ok:
          type: string
          default: "ok"

    InstrumentDataResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          oneOf:
            - type: string
            - type: array
              items:
                type: object
        idMapping:
          type: array
          items:
            $ref: '#/components/schemas/IdMapping'

    IdMapping:
      type: object
      properties:
        ExtStudyID:
          type: string
        CandID:
          type: string

    CandidatesResponse:
      type: object
      properties:
        Candidates:
          type: array
          items:
            $ref: '#/components/schemas/CandidateObject'

    CandidateObject:
      type: object
      properties:
        CandID:
          type: string
        Project:
          type: string
        PSCID:
          type: string
        Site:
          type: string
        DoB:
          type: string
          format: date
        Sex:
          type: string
          enum: [Male, Female, Other]

    CandidateCreateRequest:
      type: object
      properties:
        Candidate:
          type: object
          required: [Project, DoB, Sex, Site]
          properties:
            Project:
              type: string
            PSCID:
              type: string
            DoB:
              type: string
              format: date
            Sex:
              type: string
              enum: [Male, Female, Other]
            Site:
              type: string

    VisitObject:
      type: object
      properties:
        Meta:
          type: object
          properties:
            CandID:
              type: string
            Visit:
              type: string
            Site:
              type: string
            Project:
              type: string
        Stages:
          type: object

    VisitCreateRequest:
      type: object
      properties:
        Meta:
          type: object
          properties:
            CandID:
              type: string
            Visit:
              type: string
            Site:
              type: string
            Project:
              type: string

    VisitInstrumentsResponse:
      type: object
      properties:
        Meta:
          type: object
        Instruments:
          type: array
          items:
            type: string

    InstrumentData:
      type: object
      properties:
        Meta:
          type: object
          properties:
            Instrument:
              type: string
            Visit:
              type: string
            CandID:
              type: string
            DDE:
              type: boolean
        Data:
          type: object
          additionalProperties: true

    InstrumentDataRequest:
      type: object
      properties:
        Meta:
          type: object
          properties:
            Instrument:
              type: string
            Visit:
              type: string
            CandID:
              type: string
        Data:
          type: object
          additionalProperties: true

    ProjectsResponse:
      type: object
      properties:
        Projects:
          type: array
          items:
            type: string

    ProjectResponse:
      type: object
      properties:
        Meta:
          type: object
        Instruments:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InstrumentMeta'

    InstrumentMeta:
      type: object
      properties:
        FullName:
          type: string
        Subgroup:
          type: string
        DoubleDataEntryEnabled:
          type: boolean

    InstrumentsResponse:
      type: object
      properties:
        Instruments:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InstrumentMeta'

    SitesResponse:
      type: object
      properties:
        Sites:
          type: array
          items:
            $ref: '#/components/schemas/Site'

    Site:
      type: object
      properties:
        Name:
          type: string
        Alias:
          type: string

tags:
  - name: Authentication
    description: JWT authentication
  - name: InstrumentManager
    description: |
      Instrument installation and bulk data upload.
      Configure: `$config->setHost($baseUrl)` (no `/api/{version}`)
  - name: Candidates
    description: Candidate management
  - name: Visits
    description: Visit/timepoint management
  - name: Instruments
    description: Per-candidate instrument data
  - name: Projects
    description: Project information
  - name: Sites
    description: Site information