openapi: 3.0.1
info:
  title: LORIS - REST API endpoints
  description: |
    LORIS REST API for clinical data ingestion and management.
    Standard HTTP error codes are used. Responses contain either an empty body or a JSON object.
  contact:
    name: LORIS Development Team
    url: https://github.com/aces/loris
  license:
    name: GNU Public License, Version 3
    url: https://opensource.org/licenses/GPL-3.0
  version: 0.0.4-dev

servers:
  - url: '{protocol}://{host}/api/{version}'
    variables:
      protocol:
        default: https
        enum: [http, https]
      host:
        default: demo.loris.ca
        description: LORIS instance hostname
      version:
        default: v0.0.4-dev
        enum: [v0.0.3, v0.0.3-dev, v0.0.4-dev, v0.0.4]

security:
  - BearerAuth: []

paths:
  # ============================================
  # AUTHENTICATION
  # ============================================
  /login:
    post:
      tags:
        - Authentication
      summary: Authenticate and obtain JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ============================================
  # INSTRUMENT MANAGER
  # ============================================
  /instrument_manager:
    post:
      tags:
        - Instrument Manager
      summary: Install instrument from LINST file or REDCap CSV
      description: |
        Create/install a new instrument in LORIS from:
        - LINST file (.linst)
        - CSV with REDCap data dictionary(s)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InstrumentInstallForm'
      responses:
        '201':
          description: Instrument created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Invalid file or format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /instrument_manager/instrument_data:
    get:
      tags:
        - Instrument Manager
      summary: Generate expected CSV headers for instrument data ingestion
      description: Either `instrument` or `instruments` must be set, not both
      parameters:
        - name: action
          in: query
          description: CREATE_SESSIONS (creates missing sessions) or VALIDATE_SESSIONS (requires sessions exist)
          required: true
          schema:
            type: string
            enum: [CREATE_SESSIONS, VALIDATE_SESSIONS]
        - name: instrument
          in: query
          description: Single instrument name
          required: false
          schema:
            type: string
        - name: instruments
          in: query
          description: Comma-separated list of instruments
          required: false
          schema:
            type: string
      responses:
        '200':
          description: CSV file with expected headers
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Instrument Manager
      summary: Bulk insert instrument data from CSV
      description: |
        Actions:
        - CREATE_SESSIONS: creates candidates/sessions if missing
        - VALIDATE_SESSIONS: fails if candidate/session doesn't exist
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InstrumentDataUploadForm'
      responses:
        '200':
          description: Validation errors occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentDataResponse'
        '201':
          description: Data inserted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentDataResponse'

  # ============================================
  # PROJECTS
  # ============================================
  /projects:
    get:
      tags:
        - Projects
      summary: Get list of projects
      operationId: getProjects
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectsResponse'

  /projects/{project}:
    get:
      tags:
        - Projects
      summary: Get project details including instruments
      operationId: getProject
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'

  /projects/{project}/instruments:
    get:
      tags:
        - Projects
      summary: Get instruments for a project
      operationId: getProjectInstruments
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Instruments list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentsResponse'

  # ============================================
  # CANDIDATES
  # ============================================
  /candidates:
    get:
      tags:
        - Candidates
      summary: Get list of candidates
      operationId: getCandidates
      responses:
        '200':
          description: List of candidates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidatesResponse'
    post:
      tags:
        - Candidates
      summary: Create a new candidate
      operationId: createCandidate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CandidateCreateRequest'
      responses:
        '201':
          description: Candidate created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidateObject'
        '400':
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: PSCID already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /candidates/{candid}:
    get:
      tags:
        - Candidates
      summary: Get candidate details
      operationId: getCandidate
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Candidate details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidateObject'
        '404':
          description: Candidate not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ============================================
  # VISITS
  # ============================================
  /candidates/{candid}/{visit}:
    get:
      tags:
        - Visits
      summary: Get visit details
      operationId: getVisit
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Visit details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisitObject'
    put:
      tags:
        - Visits
      summary: Create a new visit/timepoint
      operationId: createVisit
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VisitCreateRequest'
      responses:
        '201':
          description: Visit created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisitObject'
        '409':
          description: Visit already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ============================================
  # INSTRUMENTS (Per Candidate/Visit)
  # ============================================
  /candidates/{candid}/{visit}/instruments:
    get:
      tags:
        - Instruments
      summary: Get instruments for a visit
      operationId: getVisitInstruments
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of instruments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisitInstrumentsResponse'

  /candidates/{candid}/{visit}/instruments/{instrument}:
    get:
      tags:
        - Instruments
      summary: Get instrument data for a candidate/visit
      operationId: getInstrumentData
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
        - name: instrument
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Instrument data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentData'

    put:
      tags:
        - Instruments
      summary: Replace instrument data (nulls unspecified fields)
      operationId: putInstrumentData
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
        - name: instrument
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstrumentDataRequest'
      responses:
        '200':
          description: Data replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentData'

    patch:
      tags:
        - Instruments
      summary: Update instrument data (preserves unspecified fields)
      operationId: patchInstrumentData
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
        - name: instrument
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstrumentDataRequest'
      responses:
        '200':
          description: Data updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentData'

  # ============================================
  # SITES
  # ============================================
  /sites:
    get:
      tags:
        - Sites
      summary: Get list of sites
      operationId: getSites
      responses:
        '200':
          description: List of sites
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SitesResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # Authentication
    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username: { type: string }
        password: { type: string, format: password }

    LoginResponse:
      type: object
      properties:
        token: { type: string }

    ErrorResponse:
      type: object
      properties:
        error: { type: string }

    SuccessResponse:
      type: object
      properties:
        ok:
          type: string
          default: "ok"

    # Instrument Manager
    InstrumentInstallForm:
      type: object
      required: [install_file]
      properties:
        install_file:
          type: string
          format: binary
          description: LINST or REDCap CSV instrument

    InstrumentDataUploadForm:
      type: object
      required: [action, data_file]
      properties:
        action:
          type: string
          enum: [CREATE_SESSIONS, VALIDATE_SESSIONS]
        instrument:
          type: string
        multi_instrument:
          type: string
        data_file:
          type: string
          format: binary

    InstrumentDataResponse:
      type: object
      properties:
        success: { type: boolean }
        message:
          oneOf:
            - type: string
            - type: array
              items: { type: object }
        idMapping:
          type: array
          items:
            $ref: '#/components/schemas/IdMapping'

    IdMapping:
      type: object
      properties:
        ExtStudyID: { type: string }
        CandID: { type: string }

    # Candidates
    CandidatesResponse:
      type: object
      properties:
        Candidates:
          type: array
          items:
            $ref: '#/components/schemas/CandidateObject'

    CandidateObject:
      type: object
      properties:
        CandID: { type: string }
        Project: { type: string }
        PSCID: { type: string }
        Site: { type: string }
        DoB: { type: string, format: date }
        Sex: { type: string, enum: [Male, Female, Other] }

    CandidateCreateRequest:
      type: object
      properties:
        Candidate:
          type: object
          required: [Project, DoB, Sex, Site]
          properties:
            Project: { type: string }
            PSCID: { type: string }
            DoB: { type: string, format: date }
            Sex: { type: string, enum: [Male, Female, Other] }
            Site: { type: string }

    # Visits
    VisitObject:
      type: object
      properties:
        Meta:
          type: object
          properties:
            CandID: { type: string }
            Visit: { type: string }
            Site: { type: string }
            Project: { type: string }
        Stages:
          type: object
          properties:
            Visit:
              type: object
              properties:
                Status: { type: string, enum: [Not Started, In Progress, Pass, Failure, Withdrawal] }
                Date: { type: string, format: date }

    VisitCreateRequest:
      type: object
      properties:
        Meta:
          type: object
          properties:
            CandID: { type: string }
            Visit: { type: string }
            Site: { type: string }
            Project: { type: string }

    VisitInstrumentsResponse:
      type: object
      properties:
        Meta:
          type: object
          properties:
            CandID: { type: string }
            Visit: { type: string }
        Instruments:
          type: array
          items: { type: string }

    InstrumentData:
      type: object
      properties:
        Meta:
          type: object
          properties:
            Instrument: { type: string }
            Visit: { type: string }
            CandID: { type: string }
            DDE: { type: boolean }
        Data:
          type: object
          additionalProperties: true

    InstrumentDataRequest:
      type: object
      properties:
        Meta:
          type: object
          properties:
            Instrument: { type: string }
            Visit: { type: string }
            CandID: { type: string }
        Data:
          type: object
          additionalProperties: true

    # Projects
    ProjectsResponse:
      type: object
      properties:
        Projects:
          type: array
          items: { type: string }

    ProjectResponse:
      type: object
      properties:
        Meta:
          type: object
          properties:
            Project: { type: string }
        Instruments:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InstrumentMeta'

    InstrumentMeta:
      type: object
      properties:
        FullName: { type: string }
        Subgroup: { type: string }
        DoubleDataEntryEnabled: { type: boolean }

    InstrumentsResponse:
      type: object
      properties:
        Instruments:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InstrumentMeta'

    # Sites
    SitesResponse:
      type: object
      properties:
        Sites:
          type: array
          items:
            $ref: '#/components/schemas/Site'

    Site:
      type: object
      properties:
        Name: { type: string }
        Alias: { type: string }
