openapi: 3.0.1
info:
  title: LORIS - REST API endpoints
  description: The LORIS API uses standard HTTP error codes. Responses contain either an empty body or a JSON object.
  contact:
    name: LORIS Development Team
    url: https://github.com/aces/loris
  license:
    name: GNU Public License, Version 3
    url: https://opensource.org/licenses/GPL-3.0
  version: 0.0.3

servers:
  - url: /

security:
  - ApiKeyAuth: []

paths:
  /instrument_manager:
    post:
      tags:
        - Instrument Manager
      summary: Install an instrument from a LINST file or REDCap data dictionary
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InstrumentManagerForm'
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: string
                    default: "ok"
                    description: Contains the string "ok"

  /instrument_manager/instrument_data:
    get:
      tags:
        - Instrument Data
      summary: Generate CSV headers for one or more instruments
      description: Either `instrument` or `instruments` must be set, not both.
      parameters:
        - name: action
          in: query
          description: "Either CREATE_SESSIONS or VALIDATE_SESSIONS. The latter is used when all sessions already exist."
          required: true
          schema:
            type: string
            enum:
              - CREATE_SESSIONS
              - VALIDATE_SESSIONS
        - name: instrument
          in: query
          description: Single instrument name
          required: false
          schema:
            type: string
        - name: instruments
          in: query
          description: Comma-separated list of instruments
          required: false
          schema:
            type: string
      responses:
        '200':
          description: CSV file with expected headers
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

    post:
      tags:
        - Instrument Data
      summary: Upload CSV to insert instrument data
      description: |
        CREATE_SESSIONS: creates missing candidates/sessions.  
        VALIDATE_SESSIONS: fails if any candidate/session is missing.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InstrumentDataForm'
      responses:
        '200':
          description: Validation error(s) occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether insertion succeeded
                  message:
                    type: string
                    description: Success or error messages
        '201':
          description: Successfully inserted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  idMapping:
                    type: array
                    description: Maps external PSCID to internal CandID
                    items:
                      $ref: '#/components/schemas/IdMapping'

components:
  schemas:
    InstrumentManagerForm:
      type: object
      required:
        - install_file
      properties:
        install_file:
          type: string
          format: binary
          description: "Instrument to install. Can be a LINST file (.linst) or a CSV with REDCap data dictionary."

    InstrumentDataForm:
      type: object
      required:
        - action
        - data_file
      properties:
        action:
          type: string
          enum:
            - CREATE_SESSIONS
            - VALIDATE_SESSIONS
          description: "CREATE_SESSIONS: creates missing candidates/sessions. VALIDATE_SESSIONS: fails if missing."
        instrument:
          type: string
          description: Single instrument name
        multiInstrument:
          type: string
          description: "Set to 'true' if uploading a multi-instrument CSV"
        data_file:
          type: string
          format: binary
          description: CSV file containing instrument data. Headers must match instrument(s).

    IdMapping:
      type: object
      properties:
        ExtStudyID:
          type: string
          description: External candidate ID (PSCID)
        CandID:
          type: string
          description: Internal LORIS candidate ID
