openapi: 3.0.1
info:
  title: LORIS - REST API endpoints
  description: |
    LORIS REST API for clinical data ingestion pipelines.
    Authentication via JWT - POST /login to get token, use as "Bearer <token>".
  contact:
    name: LORIS Development Team
    url: https://github.com/aces/loris
  license:
    name: GNU Public License, Version 3
    url: https://opensource.org/licenses/GPL-3.0
  version: 0.0.4-dev

servers:
  - url: '{protocol}://{host}/api/v0.0.4-dev'
    variables:
      protocol:
        default: https
        enum: [http, https]
      host:
        default: demo.loris.ca

security:
  - BearerAuth: []

paths:
  # ============================================
  # AUTHENTICATION
  # ============================================
  /login:
    post:
      tags:
        - Authentication
      summary: Authenticate and obtain JWT token
      operationId: login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ============================================
  # INSTRUMENT MANAGER - Bulk CSV Upload
  # (Used by ClinicalPipeline.uploadInstrumentCSV)
  # ============================================
  /instrument_manager:
    post:
      tags:
        - InstrumentManager
      summary: Create instrument from LINST or REDCap data dictionary
      operationId: createInstrument
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InstrumentManagerForm'
      responses:
        '201':
          description: Instrument created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /instrument_manager/instrument_data:
    get:
      tags:
        - InstrumentManager
      summary: Get expected CSV headers for instrument data
      description: |
        Returns CSV with expected headers for the specified instrument(s).
        Either "instrument" OR "instruments" must be set, not both.
      operationId: getInstrumentDataHeaders
      parameters:
        - name: action
          in: query
          description: CREATE_SESSIONS or VALIDATE_SESSIONS
          required: true
          schema:
            type: string
            enum: [CREATE_SESSIONS, VALIDATE_SESSIONS]
        - name: instrument
          in: query
          description: Single instrument name
          required: false
          schema:
            type: string
        - name: instruments
          in: query
          description: Multiple instrument names (comma-separated)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: CSV with expected headers
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

    post:
      tags:
        - InstrumentManager
      summary: Bulk insert instrument data from CSV
      description: |
        Upload CSV file to insert data for one or more instruments.
        CREATE_SESSIONS mode will create candidates/sessions if they don't exist.
        VALIDATE_SESSIONS mode requires all sessions to already exist.
      operationId: uploadInstrumentData
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InstrumentDataUploadForm'
      responses:
        '200':
          description: Validation errors occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentDataResponse'
        '201':
          description: Data inserted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentDataResponse'

  # ============================================
  # PROJECTS - Check instruments exist
  # ============================================
  /projects:
    get:
      tags:
        - Projects
      summary: Get list of projects
      operationId: getProjects
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectsResponse'

  /projects/{project}:
    get:
      tags:
        - Projects
      summary: Get project details including instruments
      operationId: getProject
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectResponse'

  /projects/{project}/instruments:
    get:
      tags:
        - Projects
      summary: Get instruments for a project
      operationId: getProjectInstruments
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Instruments list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentsResponse'

  # ============================================
  # CANDIDATES
  # ============================================
  /candidates:
    get:
      tags:
        - Candidates
      summary: Get list of candidates
      operationId: getCandidates
      responses:
        '200':
          description: List of candidates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidatesResponse'

    post:
      tags:
        - Candidates
      summary: Create a new candidate
      operationId: createCandidate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CandidateCreateRequest'
      responses:
        '201':
          description: Candidate created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidateObject'
        '409':
          description: PSCID already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /candidates/{candid}:
    get:
      tags:
        - Candidates
      summary: Get candidate details
      operationId: getCandidate
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Candidate details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandidateObject'

  # ============================================
  # VISITS
  # ============================================
  /candidates/{candid}/{visit}:
    get:
      tags:
        - Visits
      summary: Get visit details
      operationId: getVisit
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Visit details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisitObject'

    put:
      tags:
        - Visits
      summary: Create a new visit
      operationId: createVisit
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VisitCreateRequest'
      responses:
        '201':
          description: Visit created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisitObject'

  # ============================================
  # INDIVIDUAL INSTRUMENT DATA
  # ============================================
  /candidates/{candid}/{visit}/instruments:
    get:
      tags:
        - Instruments
      summary: Get instruments for a visit
      operationId: getVisitInstruments
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of instruments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisitInstrumentsResponse'

  /candidates/{candid}/{visit}/instruments/{instrument}:
    get:
      tags:
        - Instruments
      summary: Get instrument data for a candidate/visit
      operationId: getInstrumentData
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
        - name: instrument
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Instrument data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentData'

    put:
      tags:
        - Instruments
      summary: Replace instrument data
      operationId: putInstrumentData
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
        - name: instrument
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstrumentDataRequest'
      responses:
        '200':
          description: Data replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentData'

    patch:
      tags:
        - Instruments
      summary: Update instrument data
      operationId: patchInstrumentData
      parameters:
        - name: candid
          in: path
          required: true
          schema:
            type: string
        - name: visit
          in: path
          required: true
          schema:
            type: string
        - name: instrument
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstrumentDataRequest'
      responses:
        '200':
          description: Data updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstrumentData'

  # ============================================
  # SITES
  # ============================================
  /sites:
    get:
      tags:
        - Sites
      summary: Get list of sites
      operationId: getSites
      responses:
        '200':
          description: List of sites
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SitesResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # ============================================
    # Authentication
    # ============================================
    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
          format: password

    LoginResponse:
      type: object
      properties:
        token:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string

    SuccessResponse:
      type: object
      properties:
        ok:
          type: string
          default: "ok"

    # ============================================
    # Instrument Manager (Bulk Upload)
    # ============================================
    InstrumentManagerForm:
      type: object
      properties:
        install_file:
          type: string
          format: binary
          description: LINST file or REDCap CSV

    InstrumentDataUploadForm:
      type: object
      required: [action, data_file]
      properties:
        action:
          type: string
          enum: [CREATE_SESSIONS, VALIDATE_SESSIONS]
          description: CREATE_SESSIONS creates missing candidates/sessions
        instrument:
          type: string
          description: Single instrument name
        multi-instrument:
          type: string
          description: Multiple instruments flag
        data_file:
          type: string
          format: binary
          description: CSV with instrument data (headers must match)

    InstrumentDataResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Whether insertion was successful
        message:
          oneOf:
            - type: string
            - type: array
              items:
                type: object
          description: Success message or validation errors
        idMapping:
          type: array
          items:
            $ref: '#/components/schemas/IdMapping'
          description: Mapping of external to internal IDs

    IdMapping:
      type: object
      properties:
        ExtStudyID:
          type: string
          description: External study ID (PSCID)
        CandID:
          type: string
          description: LORIS candidate ID

    # ============================================
    # Candidates
    # ============================================
    CandidatesResponse:
      type: object
      properties:
        Candidates:
          type: array
          items:
            $ref: '#/components/schemas/CandidateObject'

    CandidateObject:
      type: object
      properties:
        CandID:
          type: string
        Project:
          type: string
        PSCID:
          type: string
        Site:
          type: string
        DoB:
          type: string
          format: date
        Sex:
          type: string
          enum: [Male, Female, Other]

    CandidateCreateRequest:
      type: object
      properties:
        Candidate:
          type: object
          required: [Project, DoB, Sex, Site]
          properties:
            Project:
              type: string
            PSCID:
              type: string
            DoB:
              type: string
              format: date
            Sex:
              type: string
              enum: [Male, Female, Other]
            Site:
              type: string

    # ============================================
    # Visits
    # ============================================
    VisitObject:
      type: object
      properties:
        Meta:
          type: object
          properties:
            CandID:
              type: string
            Visit:
              type: string
            Site:
              type: string
            Project:
              type: string
        Stages:
          type: object
          properties:
            Visit:
              $ref: '#/components/schemas/StageObject'

    StageObject:
      type: object
      properties:
        Status:
          type: string
          enum: [Not Started, In Progress, Pass, Failure, Withdrawal]
        Date:
          type: string
          format: date

    VisitCreateRequest:
      type: object
      properties:
        Meta:
          type: object
          properties:
            CandID:
              type: string
            Visit:
              type: string
            Site:
              type: string
            Project:
              type: string

    VisitInstrumentsResponse:
      type: object
      properties:
        Meta:
          type: object
          properties:
            CandID:
              type: string
            Visit:
              type: string
        Instruments:
          type: array
          items:
            type: string

    # ============================================
    # Individual Instrument Data
    # ============================================
    InstrumentData:
      type: object
      properties:
        Meta:
          type: object
          properties:
            Instrument:
              type: string
            Visit:
              type: string
            CandID:
              type: string
            DDE:
              type: boolean
        Data:
          type: object
          additionalProperties: true

    InstrumentDataRequest:
      type: object
      properties:
        Meta:
          type: object
          properties:
            Instrument:
              type: string
            Visit:
              type: string
            CandID:
              type: string
        Data:
          type: object
          additionalProperties: true

    # ============================================
    # Projects
    # ============================================
    ProjectsResponse:
      type: object
      properties:
        Projects:
          type: array
          items:
            type: string

    ProjectResponse:
      type: object
      properties:
        Meta:
          type: object
          properties:
            Project:
              type: string
        Instruments:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InstrumentMeta'

    InstrumentMeta:
      type: object
      properties:
        FullName:
          type: string
        Subgroup:
          type: string
        DoubleDataEntryEnabled:
          type: boolean

    InstrumentsResponse:
      type: object
      properties:
        Instruments:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/InstrumentMeta'

    # ============================================
    # Sites
    # ============================================
    SitesResponse:
      type: object
      properties:
        Sites:
          type: array
          items:
            $ref: '#/components/schemas/Site'

    Site:
      type: object
      properties:
        Name:
          type: string
        Alias:
          type: string

tags:
  - name: Authentication
    description: Login and JWT token
  - name: InstrumentManager
    description: Bulk CSV upload (used by ClinicalPipeline)
  - name: Projects
    description: Project and instrument info
  - name: Candidates
    description: Candidate management
  - name: Visits
    description: Visit/timepoint management
  - name: Instruments
    description: Individual instrument data operations
  - name: Sites
    description: Site information
