<?php
/**
 * IdMappingTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LORIS - REST API endpoints
 *
 * The LORIS API uses standard HTTP error codes. Responses contain either an empty body or a JSON object.
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LORISClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * IdMappingTest Class Doc Comment
 *
 * @category    Class
 * @description IdMapping
 * @package     LORISClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IdMappingTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IdMapping"
     */
    public function testIdMapping()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "extStudyID"
     */
    public function testPropertyExtStudyID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "candID"
     */
    public function testPropertyCandID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
