<?php
/**
 * ScriptAsyncResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LORIS API
 *
 * LORIS REST API and Module endpoints.  ## Server Configuration | Type | Configuration | Endpoints | | --- | --- | --- | | REST API | `setHost(\"{$baseUrl}/api/{$version}\")` | /login, /candidates, /projects, /sites | | Module | `setHost($baseUrl)` | /instrument_manager/_*, /cbigr_api/script/_* |
 *
 * The version of the OpenAPI document: 0.0.4-dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LORISClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ScriptAsyncResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ScriptAsyncResponse
 * @package     LORISClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ScriptAsyncResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ScriptAsyncResponse"
     */
    public function testScriptAsyncResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "job_id"
     */
    public function testPropertyJobId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pid"
     */
    public function testPropertyPid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "script"
     */
    public function testPropertyScript()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "command"
     */
    public function testPropertyCommand()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "log_file"
     */
    public function testPropertyLogFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tail_cmd"
     */
    public function testPropertyTailCmd()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
