<?php
/**
 * VisitCreateTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LORIS API
 *
 * LORIS (Longitudinal Online Research and Imaging System) REST API for managing clinical neuroimaging and behavioral research data.
 *
 * The version of the OpenAPI document: 0.0.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LORISClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VisitCreateTest Class Doc Comment
 *
 * @category    Class
 * @description VisitCreate
 * @package     LORISClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VisitCreateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VisitCreate"
     */
    public function testVisitCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "candID"
     */
    public function testPropertyCandID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "visit"
     */
    public function testPropertyVisit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "battery"
     */
    public function testPropertyBattery()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
