<?php
/**
 * VisitObjectTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LORIS - REST API endpoints
 *
 * LORIS REST API for clinical data ingestion and management. Standard HTTP error codes are used. Responses contain either an empty body or a JSON object.
 *
 * The version of the OpenAPI document: 0.0.4-dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LORISClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VisitObjectTest Class Doc Comment
 *
 * @category    Class
 * @description VisitObject
 * @package     LORISClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VisitObjectTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VisitObject"
     */
    public function testVisitObject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "stages"
     */
    public function testPropertyStages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
