<?php
/**
 * AuthenticationApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LORIS API
 *
 * LORIS (Longitudinal Online Research and Imaging System) REST API for managing clinical neuroimaging and behavioral research data.
 *
 * The version of the OpenAPI document: 0.0.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace LORISClient\Test\Api;

use \LORISClient\Configuration;
use \LORISClient\ApiException;
use \LORISClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AuthenticationApiTest Class Doc Comment
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuthenticationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for authenticate
     *
     * Authenticate and obtain JWT token.
     *
     */
    public function testAuthenticate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
