<?php
/**
 * CandidatesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LORIS REST API
 *
 * LORIS REST API and Module endpoints.  ## Server Configuration  This schema has TWO types of endpoints with different base URLs:  | Type | Base URL | Endpoints | |------|----------|-----------| | REST API (versioned) | `{baseUrl}/api/{version}` | /login, /candidates, /projects, /sites | | Module (non-versioned) | `{baseUrl}` (root) | /instrument_manager, /instrument_manager/instrument_data |  **InstrumentManager endpoints use path-level server overrides** to specify the non-versioned base URL. When using `InstrumentManagerApi`, configure with base URL only (no `/api/{version}`).
 *
 * The version of the OpenAPI document: 0.0.4-dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace LORISClient\Test\Api;

use \LORISClient\Configuration;
use \LORISClient\ApiException;
use \LORISClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CandidatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CandidatesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createCandidate
     *
     * Create a new candidate.
     *
     */
    public function testCreateCandidate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCandidate
     *
     * Get candidate details.
     *
     */
    public function testGetCandidate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCandidates
     *
     * List all candidates.
     *
     */
    public function testGetCandidates()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
