<?php
/**
 * ClinicalApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LORIS API
 *
 * LORIS (Longitudinal Online Research and Imaging System) REST API for managing clinical neuroimaging and behavioral research data.
 *
 * The version of the OpenAPI document: 0.0.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace LORISClient\Test\Api;

use \LORISClient\Configuration;
use \LORISClient\ApiException;
use \LORISClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ClinicalApiTest Class Doc Comment
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClinicalApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createCandidate
     *
     * Create a new candidate.
     *
     */
    public function testCreateCandidate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTimepoint
     *
     * Create timepoint/visit.
     *
     */
    public function testCreateTimepoint()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCandidate
     *
     * Get candidate details.
     *
     */
    public function testGetCandidate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCandidates
     *
     * Get list of candidates.
     *
     */
    public function testGetCandidates()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInstrumentData
     *
     * Get instrument data.
     *
     */
    public function testGetInstrumentData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInstruments
     *
     * Get list of instruments.
     *
     */
    public function testGetInstruments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVisit
     *
     * Get visit/timepoint information.
     *
     */
    public function testGetVisit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadInstrumentCSV
     *
     * Upload instrument CSV file.
     *
     */
    public function testUploadInstrumentCSV()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadInstrumentData
     *
     * Upload instrument data.
     *
     */
    public function testUploadInstrumentData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
