<?php
/**
 * InstrumentManagerApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LORIS API
 *
 * LORIS REST API and Module endpoints.  ## Server Configuration | Type | Configuration | Endpoints | | --- | --- | --- | | REST API | `setHost(\"{$baseUrl}/api/{$version}\")` | /login, /candidates, /projects, /sites | | Module | `setHost($baseUrl)` | /instrument_manager/_*, /cbigr_api/script/_* |
 *
 * The version of the OpenAPI document: 0.0.4-dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace LORISClient\Test\Api;

use \LORISClient\Configuration;
use \LORISClient\ApiException;
use \LORISClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InstrumentManagerApiTest Class Doc Comment
 *
 * @category Class
 * @package  LORISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InstrumentManagerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getInstrumentDataHeaders
     *
     * Get expected CSV or TSV headers for instrument data upload. Requires format query param (LORIS_CSV/REDCAP_CSV/BIDS_TSV)..
     *
     */
    public function testGetInstrumentDataHeaders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for installInstrument
     *
     * Install instrument from a LINST file, a BIDS phenotype sidecar (json), or a REDCap data dictionary (csv). Sends instrument_type field (bids/linst/redcap)..
     *
     */
    public function testInstallInstrument()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadInstrumentData
     *
     * Bulk upload instrument data from CSV or TSV file. Sends format (LORIS_CSV/REDCAP_CSV/BIDS_TSV) and strict (true/false) fields. Client auto-detects REDCap CSV via redcap_event_name column..
     *
     */
    public function testUploadInstrumentData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
